---
language: 'python'
python:
  - '2.7'
  - '3.4'

before_install:
  - 'pip install setuptools pytest'

install:
  - 'pip install --editable .'
  - 'npm --prefix flask_webpack_current/tests/test_app install flask_webpack_current/tests/test_app'

script:
  - 'npm --prefix flask_webpack_current/tests/test_app run build'
  - 'py.test flask_webpack_current/tests/test_app/tests'
